### ISSUE TITLE
CODE ISSUE; #2

### ISSUE THREAD

**Issue by JoeBanks13** [CenterCity/CenterCity#3]
You did something wrong in the readme

```js
// Current - Wrong
const require = center-city()
// Correct - Right
const centercity = require('center-city')
```

Your welcome 😄

**Comment by JoeBanks13** [comment]
Also you can't have `-` in variable names

**Comment by CenterCity** [comment]
@JoeBanks13 Thank you for reporting this bug, this has been fixed by the creator of the GitHub.


We will be closing this issue as there is no need to keep it open. If you have any more questions or concerns please contact us by dropping a ticket.

Thank you.
