### ISSUE TITLE
Guess what

### ISSUE THREAD

**Issue by JoeBanks13** [CenterCity/CenterCity#4]
Ok you did more things wrong
On the line to check if centre city's online, online should be a quoted string

Also you need to set names for your required modules 

```js
// Bad
const require('centercity')
// Good
const centercity = require('centercity')
```

If you want to make this I encourage you to actually learn what your doing and not be an idiot like your being now

**Comment by CenterCity** [comment]
Alrighty, we will look into this.

**Comment by CenterCity** [comment]
Hm, alright. We have found the error in the code we are quite sorry for any confusion on anything. 


Thank you, for reporting the bug or problem to us we appreciate it.
